// data/dashboardData.ts
export const dashboardData = {
  Users: [
    { month: "Jan", value: 400 },
    { month: "Feb", value: 600 },
    { month: "Mar", value: 900 },
    { month: "Apr", value: 1200 },
    { month: "May", value: 1500 },
    { month: "Jun", value: 1700 },
    { month: "Jul", value: 2000 },
    { month: "Aug", value: 2200 },
    { month: "Sep", value: 2500 },
    { month: "Oct", value: 2800 },
    { month: "Nov", value: 3000 },
    { month: "Dec", value: 3300 },
  ],
  Groups: [
    { month: "Jan", value: 100 },
    { month: "Feb", value: 200 },
    { month: "Mar", value: 300 },
    { month: "Apr", value: 450 },
    { month: "May", value: 500 },
    { month: "Jun", value: 600 },
    { month: "Jul", value: 650 },
    { month: "Aug", value: 700 },
    { month: "Sep", value: 750 },
    { month: "Oct", value: 800 },
    { month: "Nov", value: 850 },
    { month: "Dec", value: 900 },
  ],
  Posts: [
    { month: "Jan", value: 50 },
    { month: "Feb", value: 80 },
    { month: "Mar", value: 120 },
    { month: "Apr", value: 200 },
    { month: "May", value: 300 },
    { month: "Jun", value: 350 },
    { month: "Jul", value: 400 },
    { month: "Aug", value: 450 },
    { month: "Sep", value: 500 },
    { month: "Oct", value: 550 },
    { month: "Nov", value: 600 },
    { month: "Dec", value: 650 },
  ],
  Pages: [
    { month: "Jan", value: 30 },
    { month: "Feb", value: 50 },
    { month: "Mar", value: 70 },
    { month: "Apr", value: 100 },
    { month: "May", value: 120 },
    { month: "Jun", value: 140 },
    { month: "Jul", value: 160 },
    { month: "Aug", value: 180 },
    { month: "Sep", value: 200 },
    { month: "Oct", value: 220 },
    { month: "Nov", value: 240 },
    { month: "Dec", value: 260 },
  ],
  Events: [
    { month: "Jan", value: 10 },
    { month: "Feb", value: 15 },
    { month: "Mar", value: 20 },
    { month: "Apr", value: 25 },
    { month: "May", value: 30 },
    { month: "Jun", value: 35 },
    { month: "Jul", value: 40 },
    { month: "Aug", value: 45 },
    { month: "Sep", value: 50 },
    { month: "Oct", value: 55 },
    { month: "Nov", value: 60 },
    { month: "Dec", value: 65 },
  ],
};

/* Optional: Colors */
export const colors: Record<string, string> = {
  Users: "#3B82F6",
  Groups: "#10B981",
  Posts: "#F59E0B",
  Pages: "#EF4444",
  Events: "#8B5CF6",
};
